target_column: "Close"
timesteps: 3
scaling_method: "minmax"
val_size: 0.2
test_size: 0.1
rsi_window: 14
bb_window: 20
bb_window_dev: 2
kalman_F: [[1, 1], [0, 1]]
kalman_H: [[1, 0]]
kalman_P: [[1.0, 0.0], [0.0, 1000.0]]
kalman_R: 1.0
kalman_Q: [[0.001, 0], [0, 0.001]]

# Model training parameters
base_model:
  target_column: "Close"
  epochs: 13
  batch_size: 16
  learning_rate: 0.00047405516435924933
  hidden_dim: 38
  layer_dim: 1

enriched_model:
  target_column: "Close"
  epochs: 49
  batch_size: 16
  learning_rate: 0.0002589983780169961
  hidden_dim: 84
  layer_dim: 2

kalman_model:
  target_column: "Close"
  epochs: 35
  batch_size: 8
  learning_rate: 0.0004485480009964587
  hidden_dim: 25
  layer_dim: 1

# Model evaluation parameters
evaluation:
  target_column: "Close"
  batch_size: 10

# Hyperparameter tuning parameters
tuning:
  target_column: "Close"
  timesteps: 3
  n_trials: 150
